version: "3.9"
services:
    backend:
      build:
        context: .
        dockerfile: Dockerfile.backend
      volumes:
        - "models:/app/models"
    frontend:
      build:
        context: .
        dockerfile: Dockerfile.frontend
      tty: true
volumes:
  models:
